#!/usr/bin/env bash
# Fix container so that Nginx runs as the nginx user and listens on port 8080
sed -i 's/user  *www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80\b/listen 8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
