#!/usr/bin/env bash
# Configures a new Ubuntu machine's Nginx to include a custom
# HTTP response header X-Served-By with the server's hostname
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Add custom header X-Served-By with the hostname of the server
sudo sed -i "/http {/a \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

sudo service nginx restart
