#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend wilson_frontend
    bind *:80
    default_backend wilson_backend

backend wilson_backend
    balance roundrobin
    server 7007-web-01 34.239.0.61:80 check
    server 7007-web-02 3.87.217.227:80 check
EOF

sudo service haproxy restart
